### PR TITLE
feat: Update public ygg peers

### PR DESCRIPTION
**Pull request by stephen304**

### CODE REVIEW

**Comment by wfleurant** [comment]
I don't object to adding more peers although Arc does frown on this  

These peers are ~30ms 
```
108.175.10.127
198.58.100.240
130.250.68.53
```

These peers block pings, but their traceroutes via mass-ix to nyc-ix are probably also > 20ms rtt
```
45.76.166.128
67.205.187.55
67.205.187.55
```

The other peers are ~5ms from mass-ix.

**Comment by stephen304** [comment]
@wfleurant The main reason for this PR is because a few of the peers originally sourced from the public peers list went inactive - this is just to make sure we aren't the only working peers left in the list after several years of public peer rot.

**Comment by wfleurant** [comment]
Makes sense to me... The Popura project has some cool features to auto-add public peers based on ping times, perhaps worth the look. https://github.com/popura-network/Popura/wiki/Autopeering

**Comment by stephen304** [comment]
Yep something like that would be a nice solution

**Pull request merged**
