### PR TITLE
fixes #40 - Gateway auto configuration pipe-dream

### LINKED ISSUE #40: Gateway auto configuration pipe-dream
Here's my gateway auto configuration pipe-dream

# Server Daemon

## HTTP Endpoints accessible to ygg
* `GET /info` - Displays info
  * Gatway owner name / email, etc
  * Description - A message to the node user's UI
  * Registration required (if AllowRegistration AND WhitelistEnabled)
* `POST /register` - Takes basic information and stores requester's node key for whitelisting
  * 200 - Registration accepted
  * 400 - Registration failed
* `GET /register` - Shows the status of registration
  * 200 - Registration open
  * 202 - Registration pending approval
  * 201 - Registration successful / complete
  * 403 - Registration not allowed
* `POST /renew` - takes the source IP and finds public key, finds a free or existing IP in ygg.conf and adds a remote subnet if not exists, returns json or plain text the assigned IP, save timestamp somewhere
  * 200 - lease exists or renewed, responds with lease IP
  * 401 - Needs to register first
  * 201 - Registration pending
  * 403 - On blacklist or not on whitelist, contact node owner
  * 503 - MaxClients reached try again later

## Daemon tasks
Schedule daemon to hourly remove leases not renewed in x hours

## Daemon config
`WhitelistEnabled=true/false` Rejects `/renew` requests from keys not in whitelist if enabled
`Whitelist=[]` Whitelist array of keys to allow along with optional data, or whitelist file /shrug
`BlacklistEnabled=true/false`
`Blacklist=[]`
`AllowRegistration=true/false` Enables the `/register` endpoint, which outputs to `Registered`
`RegistrationAutoApprove=true/false` Redirects registered nodes to the `Whitelist`
`Registered=[]` Nodes that have registered, awaiting approval
`MaxClients=10` If there are <= MaxClients leases unexpired, reject `/renew` requests that do not have a lease
`LeaseTimeout=240` Number of minutes to consider lease expired

# Client Daemon
Schedules hourly daemon to POST `/renew` if a lease is saved, detect if IP changes (it could if it expired and a new lease is given), and execute the proper steps to update tunnel ip / routes

## HTTP Endpoints accessible locally
`POST /connect` - with gateway ID, on success it saves lease details for hourly daemon to renew and assigns ip/routes
  * responses could probably mirror the server http response

## Client UI
* Allows user to save an array of gateway IDs/IPs in UCI
* Web UI queries /info and /register to display gateway name/owner and registration requirements
* Web UI provides form to send registration with personal information if desired
* Web UI provides connect / disconnect button to set the gateway - on success, saves gateway to active lease file for auto renewing

### PR DESCRIPTION
**Pull request by wfleurant**
initial work for #40  

current working requests over cjdns/yggdrasil

getself 
`{"self": {"201:4522:2663:d5a6:6198:d6fe:f423:5c44": {"box_pub_key": "f25a544f725c281efe960e494a88c225e767a6634c14f4effaccedad2b0a6e74", "build_name": "yggdrasil-openwrt", "build_version": "0.3.11", "coords": "[2 22 11 13]", "subnet": "301:4522:2663:d5a6::/64"}}}`

ping
`{"method": "GET", "page": "/ping", "pathinfo": "/ping", "query_string": "", "remote_addr": "227:c456:9c9c:e192:aefe:8365:5f5a:762c", "user_agent": "curl/7.66.0"}`

### CODE REVIEW

**Review by wfleurant — COMMENTED** [review]
fine w/ this

**Comment by wfleurant** [comment]
i'll create full merge commit  
This is currently production at the :newspaper_roll:  :newspaper: spot!

**Comment by stephen304** [comment]
A couple concerns @wfleurant 

* Did we fix the python dependency issue? Does it run out of the box? Does it still compile something on first run? (that I'm fine with)
* This has no provisions for ensuring the tunnel stays configured other than the cron job I put on CH which (due to the nature of mm cl provision) causes a few packets to get lost, Ward will turn autoygg-client into a daemon that can schedule checks or use hooks. If we can hook into ifup/down events to trigger a reprovision that would be much better
* Should we hold off and use autoygg instead?

**Comment by wfleurant** [comment]
well theres no breaking changes under this merge. the fact this code runs at culture house (albeit an assuring crontab) makes it important we merge the code we create and deploy. once autoygg is introduced to meta-ib should we consider gutting this work. I'd like to merge and resolve #40 and continuing the work in python.

**Comment by stephen304** [comment]
@wfleurant That's fine, did we resolve the dependency issue that required me to use `server-daemon-blobs`? And do you think there's a simple solution to the connection interruption when re-running `mm cl provision`? If it's in master I want to document its usage (including caveats).

**Pull request merged**
